image: node:latest

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  artifacts:
    paths:
      - .
  only:
    - master

test:
  stage: test
  script:
    - npm install
    - npm run fix-style
    - npm run check-style